// Generated by CoffeeScript 1.6.3
(function() {
  var info, onReady, song, songs, uu;

  if (typeof isNodeJs === "undefined" || typeof runTest === "undefined") {
    (function() {
      var root;
      root = typeof window === "undefined" ? global : window;
      if (typeof isNodeJs === "undefined") {
        root.isNodeJs = typeof process !== "undefined";
      }
      if (typeof isWindow === "undefined") {
        root.isWindow = typeof window !== "undefined";
      }
      if (typeof isPhoneGap === "undefined") {
        root.isPhoneGap = typeof (typeof document !== "undefined" && document !== null ? document.ondeviceready : void 0) !== "undefined";
      }
      if (typeof runTest === "undefined") {
        return root.runTest = (isNodeJs ? process.argv[2] === "test" : location.hash.slice(1) === "test");
      }
    })();
  }

  onReady = function(fn) {
    if (isWindow) {
      if (document.readystate !== "complete") {
        return fn();
      } else {
        return setTimeout((function() {
          return onReady(fn);
        }), 17);
      }
    }
  };

  uu = require("uutil");

  onReady(function() {
    return console.log("HERE");
  });

  songs = {};

  song = function(title, obj) {
    obj.title = title;
    songs[title] = obj;
    return console.log(songs);
  };

  info = ["div", ""];

  song("Der sad to katte på et bord", {
    lyrics: "Der sad to katte på et bord\nKritte-ritte-rit bum bum\nDen ene på den anden glor\nKritte-ritte-rit bum bum\nSå sa'e den ene: hør min ven\nKritte-ritte-rit kritte-rit bum bum\nSku' vi ikke kravle ned igen\nKritte-ritte-rit bum bum\n\nOg da de så var kravlet ned\nKritte-ritte-rit bum bum\nSå sa'e den anden: hør min ven\nKritte-ritte-rit bum bum\nSku vi ikke kravle op igen\nKritte-ritte-rit kritte-rit bum bum\nOg så kravlede de op igen\nKritte-ritte-rit bum bum\n\nOg da de så var kravlet op\nKritte-ritte-rit bum bum\nSå sa'e den ene: hør min ven\nKritte-ritte-rit bum bum\nSku vi ikke kravle ned igen\nKritte-ritte-rit kritte-rit bum bum\nOg så kravlede de ned igen\nKritte-ritte-rit bum bum"
  });

  song("En elefant kom marcherende", {
    lyrics: "En elefant kom marcherende\nhen ad eddekoppens fine spind\nsyn's at vejen var så interessant\nat den byder op en anden elefant\n\nTo elefanter kom marcherende\nhen ad eddekoppens fine spind\nsyn's at vejen var så interessant\nat de byder op endnu en elefant\n\nTre elefanter kom marcherende\nhen ad eddekoppens fine spind\nsyn's at vejen var så interessant\nat de byder op endnu en elefant\n\n??? elefanter kom marcherende\nhen ad eddekoppens fine spind\nsyn's at vejen var så interessant\nat de byder op endnu en elefant..."
  });

  song("Lille Peter Edderkop", {
    lyrics: "Lille Peter Edderkop,\n  kravlede op ad muren.\nSå kom regnen\n  og skyllede Peter ned,\nSå kom solen\n  og tørrede Peters krop.\nLille Peter Edderkop\n  kravlede atter op."
  });

  song("Mæ siger det lille lam", {
    lyrics: "Mæ, siger det lille lam,\nmor, jeg fryser, jeg vil hjem!\nMæ, siger det store får,\nvent, til aftenklokken slår\nså skal du nok komme hjem. Mæ!\n\nRap, siger ænderne små,\nnu skal det lystigt hjemad gå.\nSove vi skal, til sol står op,\nså skal i vandet vi pjaske vor krop.\nRap, siger ænderne små. Rap!\n\nMjav, siger den lille kat,\nnu vil jeg sove så sødt i nat.\nI morgen skal vi lege igen,\nfor jeg vil helst lege dagen hen.\nMjav siger den lille kat. Mjav!\n\nPrr, siger den gamle hest,\njeg vil trækk som jeg kan bedst.\nGid jeg stod i min varme stald\nog hørte i dag ej flere knald,\nPrrr siger den gamle hest. Prrr!\n\nVov, siger den store hund,\nvåge må jeg endnu en stund,\nfare om og passe på,\nat de trygt til ro kan gå.\nVov, siger den store hund. Vov!"
  });

  song("Ride ride ranke", {
    lyrics: ""
  });

  song("Jeg gik mig over sø og land", {
    lyrics: ""
  });

  song("Mester Jakob", {
    lyrics: "Mester Jakob, \nMester Jakob.\nSover du, \nsover du?\nHører du ej klokken, \nhører du ej klokken?\nBim bam bum,\nbim bam bum."
  });

  song("Oppe i Norge der boede tre trolde", {
    lyrics: "Oppe i Norge, der boede tre trolde,\ntroldefar og troldemor og lille olle-bolle \nBØH sagde troldefar\nBøh sagde troldemor\nog den lille olle bolle sagde bare <small>bøh</small>\n\nUde i skoven, der boede tre bjørne,\nbjørnefar og bjørnemor, og lille ørne-børne\nROAR sagde bjørnefar\nRoar sagde bjørnemor\nog den lille ørne-børne sagde bare <small>roar</small>\n\nOppe på loftet, der boede tre katte,\nkattefar og kattemor, og lille katte-batte\nMJAV sagde kattefar\nMjav sagde kattemor\nog den lille katte-batte sagde bare <small>mjav</small>\n\nUde på marken, der boede tre heste,\nhestefar og hestemor, og lille heste-beste\nPRR sagde hestefar\nPrr sagde hestemor\nog den lille heste-beste sagde bare <small>prr</small>\n\nOppe i træet, der boede tre krager,\nkragefar og kragemor, og lille krage-brage\nKRRA sagde kragefar\nKrra sagde kragemor\nog den lille krage-brage sagde bare <small>krra</small>"
  });

  song("Tommelfinger, tommelfinger hvor er du", {
    lyrics: ""
  });

  song("I skoven skulle være gilde", {
    lyrics: ""
  });

  song("Langt ude i skoven", {
    lyrics: ""
  });

}).call(this);
